version: '3'

services:
  db:
    image: microsoft/mssql-server-linux:2017-GA
    environment:
      SA_PASSWORD: "sapwdlocal@123"
      ACCEPT_EULA: "Y"
    ports:
      - "10001:1433"
  solr:
    image: solr:7.4
    command: "solr-demo"
    ports:
     - "8983:8983"